### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by andresgongora** [EA7RCT/logo#1]
- [ ] Cambiar antenas por silueta de nuestras antenas reales.
- [ ] Decidir el color para elementos de fondo. El azul actual está bien.
- [ ] Rediseñar satélite, hacer mas estético.
- [ ] Añadir al fondo, por el lado de la derecha, la silueta (o comienzo de la misma) de la parte que tiene las unidades de procesado de aire.
- [ ] Limpiar SVG de elementos que ya no se usan.
- [ ] Cambiar palmeras un poco, demasiado realistas.
